INVALID_CASES = [
    # --- Basic SQL injection attempts ---
    "DROP TABLE users",
    "DELETE FROM users WHERE id = 1",
    "UPDATE users SET role='admin'",
    "INSERT INTO users VALUES ('x')",
    "data->>'name' = 'Alice'; DROP TABLE users",
    "data->>'name' = 'Bob' -- comment injection",
    "pg_terminate_backend(pid)",
    "-- just a comment",
    "/* block comment */",
    "id = ''",  # doesn't use allowed column prefix
    "data->>'age' > 30; DELETE FROM users",
    "data->>'name' = 'Alice' /* comment */",
    "' OR '1'='1'",
    "' OR '1'='1' --",
    '" OR "1"="1',
    "' OR 'x'='x' /*",
    "') OR ('1'='1",
    "') OR 1=1 --",
    "1=1 --",
    "1=1; --",
    "1=1 /*",
    "username = 'bob' -- comment",
    "' OR 1=1; /*",
    "' UNION SELECT 'a','b','c'",
    "' UNION SELECT NULL,NULL,NULL --",
    "1 UNION SELECT 1,2,3",
    "' UNION SELECT username,password FROM users --",
    "1=1; DROP TABLE users",
    "1=1; UPDATE users SET role='admin' WHERE id=1",
    "1=1; DELETE FROM users",
    "'; INSERT INTO users(name) VALUES('x'); --",
    "pg_sleep(5)=0",
    "1=1; SELECT pg_sleep(5); --",
    "IF(1=1, SLEEP(5), 0)=0",
    "WAITFOR DELAY '00:00:05' --",
    "SELECT CASE WHEN (1=1) THEN pg_sleep(5) ELSE pg_sleep(0) END --",
    "1/0 = 0",
    "' || (SELECT version()) || ' = 'x",
    "pg_terminate_backend(pid) IS NOT NULL",
    "pg_sleep(10) IS NULL",
    "LOAD_FILE('/etc/passwd') IS NOT NULL",
    "@@version_comment LIKE '%'",
    "data->>'name' = 'Alice'; DROP TABLE users",
    "data->>'name' = 'Bob' --",
    "%27 OR %271%27=%271",
    "\\' OR \\'1\\'=\\'1\\'",
    "0x61646d696e = 0x61646d696e",
    "char(97)+char(100)+char(109)='adm'",
    "OR/**/1=1",
    "OR%09%09%091=1",
    "OR 1=1",
    "OR 1=1; -- -",
    "1=1/*comment*/",
    "record.data->>'name' = 'Alice'", # invalid prefix
    "public.record.id = 1",
    "id = 1",
    "record_id = 1",
    "project_id = '...' ",
    "\"data\"->>'name' = 'Alice'", # quoted
    "\"r\".\"data\"->>'name' = 'Alice'",
    "DATA->>'name' = 'Alice'", # uppercase
    "R.DATA->>'name' = 'Alice'",
    "d\\u0061t\\u0061->>'name' = 'Alice'", # obfuscation
    "U&'data'->>'name' = 'Alice'",
    "X'64617461'->>'name' = 'Alice'",
    "drop table public.record",
    "truncate public.record",
    "delete from public.record",
    "insert into public.record (data) values ('{}')",
    "update public.record set data = '{}'",
    "alter table public.record add column x int",
    "create table test (id int)",
    "comment on table public.record is 'test'",
    "grant all on public.record to public",
    "revoke all on public.record from public",
    # --- SELECT * variations (CRITICAL: must reject all) ---
    {"select": "*"},
    {"select": "*, data->>'name'"},
    {"select": "data->>'name', *"},
    {"select": "r.*"},
    {"select": "public.record.*"},
    {"select": "record.*"},
    {"select": "t.*"},
    {"select": "alias.*"},
    # Note: count(*) should be allowed as it's an aggregate, not column selection
    "admin' UNION SELECT 1,2,3--",
    "admin' UNION SELECT NULL,NULL,NULL--",
    "admin' UNION SELECT 'a','b','c'--",
    "' UNION SELECT 1,2,3--",
    "' UNION SELECT NULL,NULL,NULL--",
    "1' UNION SELECT 1,2,3--",
    "1' UNION SELECT NULL,NULL,NULL--",
    "1 UNION SELECT 1,2,3--",
    "1 UNION SELECT NULL,NULL,NULL--",
    "' OR 1=1--",
    "1' OR 1=1--",
    "1 OR 1=1--",
    "' OR '1'='1'--",
    "1' OR '1'='1'--",
    "1 OR '1'='1'--",
    "%' OR '1'='1'--",
    "%' OR 1=1--",
    "admin'--",
    "admin' #",
    "admin'/*",
    "' OR 1=1 LIMIT 1--",
    "' OR 1=1 LIMIT 1#",
    "' OR 1=1 LIMIT 1/*",
    "' OR '1'='1' LIMIT 1--",
    "' OR '1'='1' LIMIT 1#",
    "' OR '1'='1' LIMIT 1/*",
    "admin' AND 1=1--",
    "admin' AND 1=1#",
    "admin' AND 1=1/*",
    "admin' AND 1=2--",
    "admin' AND 1=2#",
    "admin' AND 1=2/*",
    "' AND 1=1--",
    "' AND 1=1#",
    "' AND 1=1/*",
    "' AND 1=2--",
    "' AND 1=2#",
    "' AND 1=2/*",
    "1 AND 1=1--",
    "1 AND 1=1#",
    "1 AND 1=1/*",
    "1 AND 1=2--",
    "1 AND 1=2#",
    "1 AND 1=2/*",
    "admin' AND '1'='1'--",
    "admin' AND '1'='1'#",
    "admin' AND '1'='1'/*",
    "admin' AND '1'='2'--",
    "admin' AND '1'='2'#",
    "admin' AND '1'='2'/*",
    "' AND '1'='1'--",
    "' AND '1'='1'#",
    "' AND '1'='1'/*",
    "' AND '1'='2'--",
    "' AND '1'='2'#",
    "' AND '1'='2'/*",
    "1 AND '1'='1'--",
    "1 AND '1'='1'#",
    "1 AND '1'='1'/*",
    "1 AND '1'='2'--",
    "1 AND '1'='2'#",
    "1 AND '1'='2'/*",
    "admin' AND 'a'='a'--",
    "admin' AND 'a'='b'--",
    "admin' AND 1=1 AND 'a'='a'--",
    "admin' AND 1=1 AND 'a'='b'--",
    "admin' OR 1=1 AND 'a'='a'--",
    "admin' OR 1=1 AND 'a'='b'--",
    "1' OR 1=1 AND 'a'='a'--",
    "1' OR 1=1 AND 'a'='b'--",
    "1 OR 1=1 AND 'a'='a'--",
    "1 OR 1=1 AND 'a'='b'--",
    "' OR 1=1 AND 'a'='a'--",
    "' OR 1=1 AND 'a'='b'--",
    "admin' OR 'a'='a'--",
    "admin' OR 'a'='b'--",
    "admin' OR 1=1 AND 'a'='a'--",
    "admin' OR 1=1 AND 'a'='b'--",
    "1' OR 'a'='a'--",
    "1' OR 'a'='b'--",
    "1 OR 'a'='a'--",
    "1 OR 'a'='b'--",
    "' OR 'a'='a'--",
    "' OR 'a'='b'--",
    "admin' OR '1'='1'--",
    "admin' OR '1'='2'--",
    "1' OR '1'='1'--",
    "1' OR '1'='2'--",
    "1 OR '1'='1'--",
    "1 OR '1'='2'--",
    "' OR '1'='1'--",
    "' OR '1'='2'--",
    # --- Encoded/Obfuscated ---
    "data->>'a' = CHAR(65)", # CHAR might be disallowed
    # Note: \u0027Alice\u0027 and $quote$Alice$quote$ are valid PostgreSQL string literal syntaxes
    # They evaluate to 'Alice', so they're effectively valid queries, not injection attempts
    # --- Comment variations ---
    "data->>'a' = 'b'/**/OR/**/1=1",
    "data->>'a' = 'b'--\nOR 1=1",
    "data->>'a' = 'b'\n--\nOR 1=1",
    # --- JOIN variations ---
    "data->>'a' = 'b' JOIN record ON 1=1",
    "data->>'a' = 'b' CROSS JOIN (SELECT 1) AS t",
    # --- ORDER BY / GROUP BY specific ---
    {"order_by": "(CASE WHEN 1=1 THEN data->>'name' ELSE data->>'age' END)"},
    {"order_by": "data->>'name' LIMIT 1 OFFSET 1"}, # OFFSET/LIMIT in order by string might parse
    # --- Function abuse ---
    "jsonb_to_recordset(data->'items')", # if not in whitelist
    "jsonb_each(data)",
    "jsonb_populate_record(null::record, data)",
]
