INVALID_CASES = [
    # --- Basic SQL injection attempts ---
    "DROP TABLE users",
    "DELETE FROM users WHERE id = 1",
    "UPDATE users SET role='admin'",
    "INSERT INTO users VALUES ('x')",
    "data->>'name' = 'Alice'; DROP TABLE users",
    "data->>'name' = 'Bob' -- comment injection",
    "pg_terminate_backend(pid)",
    "-- just a comment",
    "/* block comment */",
    "id = ''",  # doesn't use allowed column prefix
    "data->>'age' > 30; DELETE FROM users",
    "data->>'name' = 'Alice' /* comment */",
    "' OR '1'='1'",
    "' OR '1'='1' --",
    '" OR "1"="1',
    "' OR 'x'='x' /*",
    "') OR ('1'='1",
    "') OR 1=1 --",
    "1=1 --",
    "1=1; --",
    "1=1 /*",
    "username = 'bob' -- comment",
    "' OR 1=1; /*",
    "' UNION SELECT 'a','b','c'",
    "' UNION SELECT NULL,NULL,NULL --",
    "1 UNION SELECT 1,2,3",
    "' UNION SELECT username,password FROM users --",
    "1=1; DROP TABLE users",
    "1=1; UPDATE users SET role='admin' WHERE id=1",
    "1=1; DELETE FROM users",
    "'; INSERT INTO users(name) VALUES('x'); --",
    "pg_sleep(5)=0",
    "1=1; SELECT pg_sleep(5); --",
    "IF(1=1, SLEEP(5), 0)=0",
    "WAITFOR DELAY '00:00:05' --",
    "SELECT CASE WHEN (1=1) THEN pg_sleep(5) ELSE pg_sleep(0) END --",
    "1/0 = 0",
    "' || (SELECT version()) || ' = 'x",
    "pg_terminate_backend(pid) IS NOT NULL",
    "pg_sleep(10) IS NULL",
    "LOAD_FILE('/etc/passwd') IS NOT NULL",
    "@@version_comment LIKE '%'",
    "data->>'name' = 'Alice'; DROP TABLE users",
    "data->>'name' = 'Bob' --",
    "%27 OR %271%27=%271",
    "\\' OR \\'1\\'=\\'1\\'",
    "0x61646d696e = 0x61646d696e",
    "char(97)+char(100)+char(109)='adm'",
    "OR/**/1=1",
    "OR%09%09%091=1",
    "OR 1=1",
    "OR 1=1; -- -",
    "1=1/*comment*/",
    "record.data->>'name' = 'Alice'", # invalid prefix
    "public.record.id = 1",
    "id = 1",
    "record_id = 1",
    "project_id = '...' ",
    "\"data\"->>'name' = 'Alice'", # quoted
    "\"r\".\"data\"->>'name' = 'Alice'",
    "DATA->>'name' = 'Alice'", # uppercase
    "R.DATA->>'name' = 'Alice'",
    "d\\u0061t\\u0061->>'name' = 'Alice'", # obfuscation
    "U&'data'->>'name' = 'Alice'",
    "X'64617461'->>'name' = 'Alice'",
    "drop table public.record",
    "truncate public.record",
    "delete from public.record",
    "insert into public.record (data) values ('{}')",
    "update public.record set data = '{}'",
    "alter table public.record add column x int",
    "create table test (id int)",
    "comment on table public.record is 'test'",
    "grant all on public.record to public",
    "revoke all on public.record from public",
]
