INVALID_CASES = [
    "data->>'role' = (SELECT pg_sleep(5))",
    "(SELECT COUNT(*) FROM users) > 0",
    "EXISTS(SELECT 1 FROM users WHERE is_admin = true)",
    "id IN (SELECT id FROM users WHERE role='admin')",
    "id = (SELECT id FROM users LIMIT 1)",
    "SELECT (SELECT MAX(id) FROM record) FROM record",
    "data->>'name' = (SELECT 'Alice')",
    "EXISTS (SELECT 1 FROM record)",
    "id IN (SELECT id FROM record)",
    "CAST((SELECT count(*) FROM users) AS text) = 'x'",
    "convert(int, (select top 1 name from users)) = 0",
    "(1=1) AND (SELECT COUNT(*) FROM users) > 0",
    "ASCII(SUBSTRING((SELECT user()),1,1)) > 64",
    "(SELECT CASE WHEN (LENGTH((SELECT password FROM users LIMIT 1))>0) THEN 1 ELSE 0 END)=1",
    "((SELECT 1 FROM users LIMIT 1) IS NOT NULL)",
    "EXISTS (SELECT 1 FROM orders o WHERE o.user_id = users.id AND o.total > 100)",
    "NOT EXISTS (SELECT 1 FROM bans b WHERE b.user_id = users.id)",
    "id IN (SELECT user_id FROM admins)",
    "EXISTS (SELECT 1 FROM payments p WHERE p.user_id = users.id AND p.amount = (SELECT MAX(amount) FROM payments))",
    "score >= ALL (SELECT score FROM benchmarks WHERE category = outer_table.category)",
    "1 = (SELECT 1)",
    "data #>> '{a,b}' = (select 'c')",
    "data -> 'a' -> 'b' -> 'c' = (select 'd')",
    "data->>'a' = (SELECT 'a' UNION SELECT 'b')",
    "data->>'a' = (SELECT 'a' INTERSECT SELECT 'a')",
    "data->>'a' = (SELECT 'a' EXCEPT SELECT 'b')",
    "EXISTS (SELECT * FROM pg_catalog.pg_tables)",
    "EXISTS (SELECT * FROM information_schema.tables)",
    "data->>'a' IN (SELECT column_name FROM information_schema.columns)",
    "data->>'a' = (SELECT current_user)",
    "data->>'a' = (SELECT session_user)",
    "data->>'a' = (SELECT version())",
    "data->>'a' = (SELECT current_database())",
    "data->>'a' = (SELECT substring(version(),1,1))",
    "data->>'a' = (SELECT ascii(substring(version(),1,1)))",
    "ORDER BY (SELECT 1)",
    "GROUP BY (SELECT 1)",
    "data->>'a' = (SELECT 1 FROM pg_sleep(5))",
    "data->>'a' = (SELECT count(*) FROM (SELECT 1 UNION SELECT 2) AS t)",
]
