INVALID_CASES = [
    "1=1",
    "TRUE",
    "FALSE",
    "NOT FALSE",
    "1::BOOLEAN",
    "0::BOOLEAN",
    "'1'::BOOLEAN",
    "'0'::BOOLEAN",
    "'true'::BOOLEAN",
    "'false'::BOOLEAN",
    "NULL IS NULL",
    "1 IS NOT NULL",
    "data->>'a' = data->>'a'",
    "lower('A') = 'a'",
    "1+1=2",
    "2*3=6",
    "10/2=5",
    "abs(-1)=1",
    "coalesce(null, 1)=1",
    "coalesce(1, 2)=1",
    "case when 1=1 then 1 else 0 end = 1",
    "case when true then 1 else 0 end = 1",
    "nullif(1,1) is null",
    "nullif(1,2) = 1",
    "data->>'a' = 'b' or 1=1",
    "data->>'a' = 'b' or 'x'='x'",
    "data->>'a' = 'b' or 0=0",
    "data->>'a' = 'b' or ''=''",
    "data->>'a' = 'b' or true",
    "data->>'a' = 'b' or not false",
    "data->>'a' = 'b' or coalesce(true, false)",
    "data->>'a' = 'b' or case when 1=1 then true else false end",
    "data->>'a' = 'b' or null is null",
    "data->>'a' = 'b' or 1 is not null",
    "(data->>'is_active')::boolean = true OR TRUE",
    "data->>'name' = 'admin' OR '1'='1'",
    "(data->>'is_active')::boolean = true OR TRUE",
    "1=1--",
    "1=1#",
    "1=1/*",
    "admin' --",
    "admin' #",
    "admin'/*",
    "' or 1=1--",
    "' or 1=1#",
    "' or 1=1/*",
    "') or '1'='1'--",
    "') or ('1'='1'--",
    "1' or '1'='1",
    "1 or '1'='1",
    "1' or 1=1",
    "1 or 1=1",
    "' or 'a'='a",
    "' or ''='",
    "'='",
    "'or'1'='1'",
    "1' or '1'='1'--",
    "1' or '1'='1'#",
    "1' or '1'='1'/*",
    "1' or 1=1--",
    "1' or 1=1#",
    "1' or 1=1/*",
    "data->>'a' = data->>'a'",
    "data->>'a' LIKE 'a%' OR '1'='1'",
    "data->>'a' = 'b' OR '1'='1' --",
    "data->>'a' = 'b' OR 1=1",
    "COALESCE(1,1)=1",
    "NULLIF(1,1) IS NULL",
    "EXISTS (SELECT 1)",
    "data->>'a' = (SELECT 'a')",
    "TRUE OR data->>'a'='b'",
    "FALSE OR TRUE",
    "NOT FALSE",
    "NOT TRUE", # not always true but constant
    "1=1 AND 2=2",
    "1=1 OR 2=2",
    "data->>'a' = 'b' AND 1=1",
    "1 < 2",
    "2 > 1",
    "1 <= 1",
    "1 >= 1",
    # --- Extended constant evaluation cases ---
    # Arithmetic tautologies
    "5+5=10",
    "100-50=50",
    "3*4=12",
    "20/4=5",
    "1+2+3=6",
    "2*3*4=24",
    "(1+2)*3=9",
    "10-5+3=8",
    "100/10/2=5",
    "-5=-5",
    "(-3)*(-2)=6",
    # COALESCE variations
    "coalesce(null, null, 1)=1",
    "coalesce(null, 2, 3)=2",
    "coalesce(5, null)=5",
    "COALESCE(NULL, NULL, 42)=42",
    "coalesce(null, 1+1)=2",
    "coalesce(null, 10/2)=5",
    # NULLIF variations
    "nullif(5, 5) is null",
    "nullif(10, 10) is null",
    "NULLIF(42, 42) IS NULL",
    "nullif(1+1, 2) is null",
    "nullif(10/2, 5) is null",
    "nullif(3, 4)=3",
    "nullif(100, 50)=100",
    # ABS variations
    "abs(5)=5",
    "abs(-5)=5",
    "abs(-100)=100",
    "abs(0)=0",
    # Combined expressions
    "coalesce(null, abs(-5))=5",
    "abs(coalesce(null, -10))=10",
    "nullif(abs(-1), 1) is null",
    "coalesce(nullif(1,1), 2)=2",
    "abs(-1)+abs(-2)=3",
    "coalesce(null, 1)+coalesce(null, 2)=3",
    # Nested arithmetic
    "(10/2)+(3*2)=11",
    "((1+2)*(3+4))=21",
    "(100-50)/(10/2)=10",
    # Edge cases with zero
    "0+0=0",
    "0*100=0",
    "0-0=0",
    # String comparisons (should also be caught)
    "'hello'='hello'",
    "'test'='test'",
    "''=''",
    # --- More edge cases for constant evaluation ---
    # Multiple operations chained
    "1+2+3+4=10",
    "2*2*2*2=16",
    "100/2/5=10",
    "10-5-3=2",
    # Mixed operations
    "1+2*3=7",
    "10-2*3=4",
    "(5+5)*(2+2)=40",
    "100/(5+5)=10",
    # COALESCE edge cases
    "coalesce(null, null, null, 1)=1",
    "coalesce(0, 1)=0",  # 0 is not null, so returns 0
    "coalesce(null, 0)=0",
    # NULLIF edge cases
    "nullif(0, 0) is null",
    "nullif('a', 'a') is null",
    "nullif('a', 'b')='a'",
    # Negative numbers
    "(-1)*(-1)=1",
    "(-10)/(-2)=5",
    "(-5)+(-5)=-10",
    "abs(-(-5))=5",
    # Floating point (integer result)
    "6/3=2",
    "9/3=3",
    "15/5=3",
    # Complex nested
    "abs(coalesce(null, -10))+abs(-5)=15",
    "coalesce(nullif(1,1), nullif(2,2), 3)=3",
    "nullif(abs(-5), 5) is null",
    "(coalesce(null, 5)+coalesce(null, 5))=10",
]
