INVALID_CASES = [
    "1=1",
    "TRUE",
    "FALSE",
    "NOT FALSE",
    "1::BOOLEAN",
    "0::BOOLEAN",
    "'1'::BOOLEAN",
    "'0'::BOOLEAN",
    "'true'::BOOLEAN",
    "'false'::BOOLEAN",
    "NULL IS NULL",
    "1 IS NOT NULL",
    "data->>'a' = data->>'a'",
    "lower('A') = 'a'",
    "1+1=2",
    "2*3=6",
    "10/2=5",
    "abs(-1)=1",
    "coalesce(null, 1)=1",
    "coalesce(1, 2)=1",
    "case when 1=1 then 1 else 0 end = 1",
    "case when true then 1 else 0 end = 1",
    "nullif(1,1) is null",
    "nullif(1,2) = 1",
    "data->>'a' = 'b' or 1=1",
    "data->>'a' = 'b' or 'x'='x'",
    "data->>'a' = 'b' or 0=0",
    "data->>'a' = 'b' or ''=''",
    "data->>'a' = 'b' or true",
    "data->>'a' = 'b' or not false",
    "data->>'a' = 'b' or coalesce(true, false)",
    "data->>'a' = 'b' or case when 1=1 then true else false end",
    "data->>'a' = 'b' or null is null",
    "data->>'a' = 'b' or 1 is not null",
    "(data->>'is_active')::boolean = true OR TRUE",
    "data->>'name' = 'admin' OR '1'='1'",
]
