AGG_EXPR = "data->>'name'"

VALID_CASES = [
    # --- Basic tests ---
    "r.data->>'name' = 'Alice'",
    "data->>'name' = 'Alice'",
    "data->>'age'::int > 30",
    "data @> '{\"verified\": true}'",
    "(data->>'score')::float >= 4.5",
    "lower(data->>'email') LIKE '%@example.com'",
    "data->'tags' ? 'premium'",
    "(data->>'status') IN ('active', 'pending')",
    "to_tsvector('english', data->>'bio') @@ plainto_tsquery('developer')",
    "(data->'meta'->>'role') = 'admin' AND (data->>'disabled')::boolean = false",
    "jsonb_array_length(data->'projects') > 0",
    "coalesce(data->>'nickname', data->>'name') = 'Anonymous'",
    "data->'preferences' @> '{\"theme\": \"dark\"}'",
    "(data->>'country') IS NOT NULL",
    "(data->'profile'->>'age')::int BETWEEN 18 AND 30",
    "jsonb_typeof(data->'settings') = 'object'",
    "(to_tsvector('english', data->>'summary') @@ phraseto_tsquery('machine learning'))",
    "(data->>'rating')::numeric * 2 > 9",
    "(data->>'joined_at')::date < current_date",
    "(data->>'department') NOT ILIKE 'sales%'",
    "data->>'value' ILIKE '%--%'",
    "data->>'pattern' LIKE '%/*comment*/%'",
    "data->>'text' ~ '^[a-zA-Z0-9_]+$'",
    "data->>'text' ~* '^[a-zA-Z0-9_]+$'",
    "data->>'text' LIKE '%;%'",
    "(data->>'id')::int = 42",
    "(data->>'price')::numeric < 99.99",
    "(data->>'score')::float >= 4.5",
    "(data->>'created_at')::timestamp > now() - interval '7 days'",
    "(data->>'birthday')::date = current_date - interval '30 years'",
    "(data->>'is_active')::boolean = true",
    "(data->>'comment')::text ILIKE '%hello%'",
    "upper(data->>'title') LIKE 'HELLO%'",
    "trim(data->>'name') = 'Alice'",
    "substring(data->>'description', 1, 5) = 'Hello'",
    "concat(data->>'first_name', ' ', data->>'last_name') = 'Alice Smith'",
    "coalesce(data->>'nickname', data->>'username', 'guest') = 'guest'",
    "length(data->>'bio') > 20",
    "jsonb_array_length(data->'items') > 1",
    "jsonb_typeof(data->'profile') = 'object'",
    "jsonb_exists(data, 'email')",
    "jsonb_exists_any(data, ARRAY['phone','email'])",
    "jsonb_exists_all(data, ARRAY['first_name','last_name'])",
    "(data->>'updated_at')::timestamp > now() - interval '1 day'",
    "date_trunc('day', (data->>'joined_at')::timestamp) = current_date::timestamp",
    "age(now(), (data->>'birthdate')::timestamp) > interval '18 years'",
    "to_timestamp(data->>'epoch', 'YYYY-MM-DD HH24:MI:SS') < now()",
    "to_tsvector('english', data->>'content') @@ plainto_tsquery('search term')",
    "to_tsvector('simple', data->>'tags') @@ phraseto_tsquery('fast car')",
    "to_tsvector('english', coalesce(data->>'summary','')) @@ plainto_tsquery('ai')",
    "data->>'username' ~ '^[a-zA-Z0-9_]{3,16}$'",
    "data->>'email' ~* '^[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,}$'",
    "(data->>'url') ~* '^https?://'",
    "data->>'comment' !~ 'spam'",
    "data->>'comment' !~* 'bannedword'",
    "(data->>'verified')::boolean = true AND (data->>'role') = 'admin'",
    "((data->>'status') = 'active' OR (data->>'status') = 'pending') AND (data->>'deleted')::boolean = false",
    "(data->>'priority')::int BETWEEN 1 AND 5",
    "(data->>'rating')::numeric * 2 > 9",
    "lower(coalesce(data->>'category', '')) LIKE '%tech%'",
    "(to_tsvector('english', data->>'notes') @@ plainto_tsquery('performance')) AND jsonb_array_length(data->'attachments') > 0",
    "(data->>'last_login')::timestamp > (now() - interval '30 days')",
    "upper(data->>'country') = 'US'",
    "(data->>'joined_at')::timestamp < now() AND jsonb_typeof(data->'settings') = 'object'",
    "data->>'timezone' IN ('UTC', 'CET', 'PST')",
    "data->'arr' @> '[1,2,3]'::jsonb",
    "data->'arr' <@ '[1,2,3,4]'::jsonb",
    "data->>'a' BETWEEN '1' AND '9'",
    "r . data ->> 'name' = 'Alice'",
    "data ->> 'name' = 'Alice'",
    "data->> 'name' = 'Alice'",
    "data ->>'name' = 'Alice'",
]
